#!/bin/sh
set -e

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

cp -r test "$tmpdir"
cd "$tmpdir"

ln -s /usr/lib/nodejs/iferr/iferr.js iferr.js
ln -s /usr/lib/nodejs/iferr/package.json package.json
coffee -c test/index.coffee
mocha -R spec test